version: 2

updates:
  - package-ecosystem: bundler
    directories:
      - /
      - /spec/dummy
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      component-stack:
        patterns:
          - "govuk-components"
          - "view_component"
      shared-ruby:
        patterns:
          - "*"
        group-by: dependency-name

  - package-ecosystem: npm
    directories:
      - /
      - /spec/dummy
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      frontend-stack:
        patterns:
          - "@ministryofjustice/frontend"
          - "govuk-frontend"
      shared-npm:
        patterns:
          - "*"
        group-by: dependency-name

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
