name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/rubocop.yml@main

  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        rails: ["7.2", "8.0", "8.1"]
    runs-on: ubuntu-latest
    name: Testing with Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install gems
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - name: Run Herb Linter
        run: npm run herb:lint

  dummy_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spec/dummy
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/spec/dummy/Gemfile

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: spec/dummy/package-lock.json

      - name: Install dummy npm packages
        run: npm ci

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Run dummy app CI
        run: bin/ci

      - name: Verify dummy assets build
        env:
          SECRET_KEY_BASE_DUMMY: 1
        run: bin/rails assets:precompile

  ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Assume role in Cloud Platform
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      # Login to container repository
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      # Build and push a Docker image to the container repository
      - run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY_URL }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
